### ISSUE TITLE
Need to add link to buy catalogue in store

### ISSUE THREAD

**Issue by swambold6** [stillmuseum/worksonpaper#120]
https://shop.clyffordstillmuseum.org/products/clyfford-still-the-works-on-paper

**Comment by swambold6** [comment]
@halfempty This is done, which means we need to do another push/publish/thing.

**Comment by swambold6** [comment]
http://pubs.clyffordstillmuseum.org/worksonpaperdev/downloads/

**Comment by halfempty** [comment]
@swambold6 Updated: 

http://pubs.clyffordstillmuseum.org/worksonpaper/downloads/

I manually updated this page, because it was a localized change and easier to do than running full process. So if that was the only change, please go ahead and close this issue.

On the other hand, if there were other pages changed as well, let me know and I'll run the process.

**Comment by swambold6** [comment]
@halfempty Awesome. Thanks!
