### ISSUE TITLE
Chronological sort on thumbnails

### ISSUE THREAD

**Issue by swambold6** [stillmuseum/worksonpaper#21]
Would like for the thumbnails within each section to appear in chronological order (either by Creation Date#1 or by image filename.

**Comment by halfempty** [comment]
@swambold6 I've sorted by our Date field, which is working in most cases. However, the sort gets confused by dates that are non-standard, such as "ca. 1923–33". Might one of the other fields be more consistent?

**Comment by swambold6** [comment]
@halfempty Looks like Filename#1 is almost always date first (example: "1925 PW-30_Regester2014_HR.tif"). The only instances I see in the full spreadsheet wherein that is not the case is for three items from the archives, which can come at the end as far as I'm concerned.

The Filename#1 field is not needed elsewhere. I'm creating a new field for the WP import of these objects, which will have virtually the same filenames as in the Filename#1 save for special characters removed, and "web" added to the end to indicate resizing. The same example from above reformatted for WP would appear "1925_PW30_Regester2014_web.jpg".

Helpful?

**Comment by halfempty** [comment]
@swambold6 I've created a field called "Sort Order", and coded it to sort that way. Next time we import objects we can populate it from the sheet.

**Comment by halfempty** [comment]
@swambold6 Ps. Just to elaborate on that, what about duplicating the Creation Date into a new column, and then adjusting the few that are non-standard?

**Comment by swambold6** [comment]
@halfempty I don't understand. I'm too dumb. :(

**Comment by halfempty** [comment]
@swambold6 Okay, this turned out to be a little complicated to implement, but it's in. I've saved a "v5" version of the spreadsheet to the dropbox. Notice that there's two new columns-- 

- The first is "Sort Year" and is a simplified version of the year. This will become a category, to enable filtering by that year (if we want it).
- The second is "Sort Order". This is for setting thumbnail order. It's the year, followed by a two-digit increment. I tried to take into account the day/month of creation in setting the increment, as best I could (some of the drawings from the 70's had specific dates on them).

Feel free to update these if you need to.
