### ISSUE TITLE
PDF download

### ISSUE THREAD

**Issue by swambold6** [stillmuseum/worksonpaper#27]
(Do we have an issue open for this already?)

(Last priority)

**Comment by swambold6** [comment]
@halfempty How are things looking for the PDF download?

**Comment by halfempty** [comment]
@swambold6 Long term, yes. For launch, no.

Daniel identified that we needed to upgrade PHP to run Pressbooks. At first we thought that wouldn't be possible, but then I found a way to do it. So he's back to getting the test installation of PB active on the CSM's server.

I'm going to encourage Dan to communicate via Github more often (I've created a project for PB), rather than email, so that you'll be in the loop.
